# Generated by Django 4.1.7 on 2023-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="username")),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="firstname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="lastname"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
